/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learning_javalin;

import java.nio.file.Path;

import io.javalin.Javalin;

// import io.javalin.http.staticfiles.StaticFileConfig;

public class App {


    public static void main(String[] args) {
        var app = Javalin.create( config -> {
            config.staticFiles.add( StaticFileConfig -> {
                StaticFileConfig.hostedPath = "/";
                StaticFileConfig.directory = "/public";
                
            } );
        })

        .start(8080);


        app.before(ctx -> {
            boolean sessionExists = ctx.sessionAttribute("nombre") != null; // Verificar si la sesión existe
            String path = ctx.path();
        
            if (!path.equals("/formulario.html") && !path.equals("/login") && !path.equals("/profile") && !sessionExists) {
                ctx.redirect("/formulario.html");
            } else if (path.equals("/formulario.html") && sessionExists) {
                ctx.redirect("/");
            }
        });
        
        
        app.post("/login", ctx -> {
            String usuario = ctx.formParam("nombre");
            String password = ctx.formParam("password");
        
            if (usuario == null || password == null || usuario.isEmpty() || password.isEmpty()) {
                // Error al procesar la información.
                ctx.redirect("/formulario.html");
                return;
            }
        
            ctx.sessionAttribute("nombre", usuario); // Establecer un atributo de sesión
            ctx.redirect("/");
        });
        
        app.get("/", ctx -> {
            
            String username = ctx.sessionAttribute("nombre");
            if (username != null) {
                ctx.html("<h3> Bienvenido " + username + " </h3>");
            } else {
                ctx.redirect("/formulario.html");
            }
        });
                


        
    }
}
